version: '3.8'

# =============================================================================
# 🛠️  VOICECOOP - CONFIGURATION DÉVELOPPEMENT
# =============================================================================
# Configuration Docker optimisée pour le développement local
# Usage: docker-compose -f docker-compose.dev.yml up -d
# =============================================================================

services:
  # 🗄️  PostgreSQL - Base de données locale pour développement
  postgres-dev:
    image: postgres:15-alpine
    container_name: voicecoop-postgres-dev
    environment:
      - POSTGRES_DB=voicecoop_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5433:5432"  # Port différent pour éviter les conflits
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./supabase/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./supabase/migrations:/docker-entrypoint-initdb.d/migrations
    networks:
      - voicecoop-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🗄️  Redis - Cache pour développement
  redis-dev:
    image: redis:7-alpine
    container_name: voicecoop-redis-dev
    ports:
      - "6380:6379"  # Port différent pour éviter les conflits
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    networks:
      - voicecoop-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # 📧 MailHog - Serveur email de test
  mailhog:
    image: mailhog/mailhog:latest
    container_name: voicecoop-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Interface web
    networks:
      - voicecoop-dev-network
    restart: unless-stopped

  # 🔍 Adminer - Interface base de données
  adminer:
    image: adminer:latest
    container_name: voicecoop-adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres-dev
    depends_on:
      - postgres-dev
    networks:
      - voicecoop-dev-network
    restart: unless-stopped

  # 📊 Redis Commander - Interface Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: voicecoop-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis-dev:6379
    depends_on:
      - redis-dev
    networks:
      - voicecoop-dev-network
    restart: unless-stopped

# 💾 Volumes pour développement
volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

# 🌐 Réseau de développement
networks:
  voicecoop-dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

# =============================================================================
# 🛠️  OUTILS DE DÉVELOPPEMENT DISPONIBLES
# =============================================================================
# 
# PostgreSQL Dev:     localhost:5433
# Redis Dev:          localhost:6380
# Adminer (DB UI):    http://localhost:8080
# Redis Commander:    http://localhost:8081
# MailHog (Email):    http://localhost:8025
# 
# Variables d'environnement pour .env.local:
# DATABASE_URL="postgresql://postgres:password@localhost:5433/voicecoop_dev"
# REDIS_URL="redis://localhost:6380"
# SMTP_HOST="localhost"
# SMTP_PORT="1025"
# 
# =============================================================================
