[build]
  publish = ".next"
  command = "npx prisma generate && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

# Configuration pour Next.js sur Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirections et rewrites pour Next.js App Router
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback pour Next.js - DOIT ÊTRE LE DERNIER
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Configuration des fonctions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Variables d'environnement pour Netlify
[build.environment]
  # Application
  NEXT_PUBLIC_APP_NAME = "VoiceCoop"
  NEXT_PUBLIC_APP_URL = "https://voicecoop.netlify.app"
  NODE_ENV = "production"

  # NextAuth
  NEXTAUTH_URL = "https://voicecoop.netlify.app"
  NEXTAUTH_SECRET = "voicecoop-production-secret-2024-ultra-secure"

  # Supabase
  NEXT_PUBLIC_SUPABASE_URL = "https://omtcukbtdnbvdrhlwhri.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tdGN1a2J0ZG5idmRyaGx3aHJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzEyNjIsImV4cCI6MjA3MDEwNzI2Mn0.8uHdE3MDShrv3DxdHw9TkA5gZQt8B57b96iOwxqeAiA"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tdGN1a2J0ZG5idmRyaGx3aHJpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDUzMTI2MiwiZXhwIjoyMDcwMTA3MjYyfQ.9RTNsQg_cefDbKTjArRiBvn6zRxH0tiYMRT4cOgO6BY"
  DATABASE_URL = "postgresql://postgres.omtcukbtdnbvdrhlwhri:voicecoop2024@aws-0-eu-central-1.pooler.supabase.com:6543/postgres"

# Configuration du cache
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
